# Generated by Django 4.2.2 on 2023-06-20 18:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0003_alter_task_options_task_created'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Task',
        ),
    ]
